Database:
  #SQLITE, MYSQL, MONGODB (you may add URI, example below)
  #URI: mongodb://localhost:27017
  Type: SQLITE
  IdentifierType: UUID
  Hostname: localhost
  Port: 3306
  Database: database
  Username: admin
  Password: password
Settings:
  #If true, it will help debugging loading assets and such
  Tiny-Debug: false
  #How long in ticks it will take for the pet to apply stats once spawned
  Apply-Delay: 20
  #If true, pets won't have levels and storage will count unique pets.
  Use-Simple-Storage: false
  Pet-Packing:
    Distance: 0.65
    Row-Size: 3
    Max-Pack-Size: 9
    Pivot:
      Forward: -0.25
      Up: -1.0
      Right: -2.25
Listeners:
  TinyListeners:
    DisplayLevel: false